package org.marj4n.smooth_progression.entity;

import net.minecraft.entity.EquipmentSlot;
import net.minecraft.entity.mob.HostileEntity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.util.math.random.Random;

public final class EliteEquipment {

    private static final String EQUIPMENT_TAG =
            "smoothprogression.elite_equipment_applied";

    private EliteEquipment() {
    }

    public static void apply(
            HostileEntity mob,
            int level
    ) {

        if (!mob.getCommandTags().contains(
                "smoothprogression.elite"
        )) {
            return;
        }

        // Prevent rerolling equipment on chunk reload.
        if (mob.getCommandTags().contains(EQUIPMENT_TAG)) {
            return;
        }

        Random random = mob.getRandom();

        // Mark first so equipment cannot be rerolled.
        mob.addCommandTag(EQUIPMENT_TAG);

        // Not every elite receives equipment.
        if (random.nextDouble() >= 0.75D) {
            return;
        }

        EquipmentTier tier = selectTier(level, random);

        equipArmor(mob, tier, random);
        equipWeapon(mob, tier, random);
    }

    private static EquipmentTier selectTier(
            int level,
            Random random
    ) {

        if (level <= 30) {
            return random.nextBoolean()
                    ? EquipmentTier.LEATHER
                    : EquipmentTier.IRON;
        }

        if (level <= 75) {
            return random.nextBoolean()
                    ? EquipmentTier.IRON
                    : EquipmentTier.DIAMOND;
        }

        if (level <= 150) {
            return random.nextDouble() < 0.25D
                    ? EquipmentTier.NETHERITE
                    : EquipmentTier.DIAMOND;
        }

        return random.nextDouble() < 0.70D
                ? EquipmentTier.NETHERITE
                : EquipmentTier.DIAMOND;
    }

    private static void equipArmor(
            HostileEntity mob,
            EquipmentTier tier,
            Random random
    ) {

        // Full sets become more likely at higher levels.
        double pieceChance = switch (tier) {
            case LEATHER -> 0.45D;
            case IRON -> 0.65D;
            case DIAMOND -> 0.80D;
            case NETHERITE -> 0.95D;
        };

        equipIfEmpty(
                mob,
                EquipmentSlot.HEAD,
                tier.helmet,
                pieceChance,
                random
        );

        equipIfEmpty(
                mob,
                EquipmentSlot.CHEST,
                tier.chestplate,
                pieceChance,
                random
        );

        equipIfEmpty(
                mob,
                EquipmentSlot.LEGS,
                tier.leggings,
                pieceChance,
                random
        );

        equipIfEmpty(
                mob,
                EquipmentSlot.FEET,
                tier.boots,
                pieceChance,
                random
        );
    }

    private static void equipWeapon(
            HostileEntity mob,
            EquipmentTier tier,
            Random random
    ) {

        // Preserve bows, crossbows, and modded weapons.
        if (!mob.getEquippedStack(
                EquipmentSlot.MAINHAND
        ).isEmpty()) {
            return;
        }

        if (random.nextDouble() >= 0.65D) {
            return;
        }

        mob.equipStack(
                EquipmentSlot.MAINHAND,
                new ItemStack(tier.sword)
        );

        mob.setEquipmentDropChance(
                EquipmentSlot.MAINHAND,
                0.01F
        );
    }

    private static void equipIfEmpty(
            HostileEntity mob,
            EquipmentSlot slot,
            Item item,
            double chance,
            Random random
    ) {

        // Never overwrite existing equipment.
        if (!mob.getEquippedStack(slot).isEmpty()) {
            return;
        }

        if (random.nextDouble() >= chance) {
            return;
        }

        mob.equipStack(
                slot,
                new ItemStack(item)
        );

        // Equipment generated by this system:
        // 1% chance to drop.
        mob.setEquipmentDropChance(slot, 0.01F);
    }

    private enum EquipmentTier {

        LEATHER(
                Items.LEATHER_HELMET,
                Items.LEATHER_CHESTPLATE,
                Items.LEATHER_LEGGINGS,
                Items.LEATHER_BOOTS,
                Items.WOODEN_SWORD
        ),

        IRON(
                Items.IRON_HELMET,
                Items.IRON_CHESTPLATE,
                Items.IRON_LEGGINGS,
                Items.IRON_BOOTS,
                Items.IRON_SWORD
        ),

        DIAMOND(
                Items.DIAMOND_HELMET,
                Items.DIAMOND_CHESTPLATE,
                Items.DIAMOND_LEGGINGS,
                Items.DIAMOND_BOOTS,
                Items.DIAMOND_SWORD
        ),

        NETHERITE(
                Items.NETHERITE_HELMET,
                Items.NETHERITE_CHESTPLATE,
                Items.NETHERITE_LEGGINGS,
                Items.NETHERITE_BOOTS,
                Items.NETHERITE_SWORD
        );

        private final Item helmet;
        private final Item chestplate;
        private final Item leggings;
        private final Item boots;
        private final Item sword;

        EquipmentTier(
                Item helmet,
                Item chestplate,
                Item leggings,
                Item boots,
                Item sword
        ) {

            this.helmet = helmet;
            this.chestplate = chestplate;
            this.leggings = leggings;
            this.boots = boots;
            this.sword = sword;
        }
    }
}